# Generated by Django 3.2.6 on 2021-08-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state_or_province',
        ),
        migrations.AddField(
            model_name='order',
            name='county_or_state',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
