# Generated by Django 3.2.5 on 2021-08-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210808_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='icon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
