# Generated by Django 3.2.5 on 2021-08-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_socialmediaprofile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='social.socialmediaicon'),
        ),
    ]
