# Generated by Django 3.2.5 on 2021-08-08 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_socialmediaprofile_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediaicon',
            old_name='icon',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='socialmediaprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='social.socialmediaicon'),
        ),
    ]
