# Generated by Django 3.2.5 on 2021-08-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20210808_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='active',
            field=models.BooleanField(),
        ),
    ]
